version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:8.12-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout
      
      - restore_cache:
          keys:
            - yarn-packages-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v2-{{ .Branch }}-
            - yarn-packages-v2-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Run Tests
          command: npx nightwatch index.js

      - deploy:
          name: Try Again
          command: |
            sleep 5m
            git config --global user.email "kevincolten@gmail.com"
            git config --global user.name "Kevin Colten"
            git commit --allow-empty -m "No luck"
            git push origin master
